version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  client_mobile:
    build:
      context: ./client_mobile
      dockerfile: Dockerfile
    volumes:
      - ./client_volume:/usr/src/app/mobile
  client_web:
    build:
      context: ./client_web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./client_volume:/usr/src/app/build/apk/
    depends_on:
      - server
      - client_mobile
    entrypoint: ["bash", "script.sh"]
volumes:
  client_volume: